### ISSUE TITLE
Testing new dataset

### ISSUE THREAD

**Issue by ayushsingh11** [cliang1453/BOND#1]
Hi,
Thanks for providing the code.
The code works fine with datasets given in the repository, but, if I want to use it to process some other dataset, how should I construct the "words" list given in your current datasets, which has values for the attention-mask?

**Comment by HMJiangGatech** [comment]
Hi, 
the "words", "def", "chars" are actually not used in this project. You can simply use a dataset without these terms.

**Comment by ayushsingh11** [comment]
Thanks!!
