### ISSUE TITLE
Trying BOND on new datasets and languages

### ISSUE THREAD

**Issue by dadelani** [cliang1453/BOND#13]
Thank you for the great work. Would you be able to provide the Gazetteers data and distant label generation code? I would like to try BOND on new datasets. @cliang1453 @HMJiangGatech 

Thank you in advance

**Comment by cliang1453** [comment]
Sure, could you please share your email address?

**Comment by dadelani** [comment]
Thank you Chen. I sent you an email two days ago. I can resend again.

**Comment by cliang1453** [comment]
Thanks for resending! It looks like the previous one was filtered out by the system. I've replied back with the code and data.
