### ISSUE TITLE
Distant label generation code

### ISSUE THREAD

**Issue by rtmaww** [cliang1453/BOND#15]
Thank you for the great work. Would you be able to provide the Gazetteers data and distant label generation code? I would like to try BOND on new datasets. My email address is 308874378@qq.com.

Thank you in advance!

**Comment by mayasahraoui** [comment]
Hey, did they send you the code ? I need to try BOND on new datasets too !

**Comment by cliang1453** [comment]
@mayasahraoui could you please provide your email address?

**Comment by mayasahraoui** [comment]
Sure, it's : maya.sahraoui@lip6.fr

**Comment by anindya2906** [comment]
Hi, @cliang1453..thanks for this great repo..I need to try this with some custom dataset..can you please share the code for data preparation...thanks in advance...my email is anindya_2906@yahoo.co.in

**Comment by cliang1453** [comment]
Hi @anindya2906, code sent.

**Comment by effyli** [comment]
Hi @cliang1453, thank you for the contribution. I wonder if you are able to share the code for distant labels generation and the Gazetteers you are using? Much appreciated! My email is effyli@gmail.com

**Comment by cliang1453** [comment]
Hi @effyli, could you provide me with another email address? effyli@gmail.com cannot be found.

**Comment by Automanmm** [comment]
Hi @cliang1453 , thank you for the contribution. I wonder if you are able to share the code for distant labels generation and the Gazetteers you are using? My email is wmy_mmyy@163.com, thanks very much!

**Comment by cliang1453** [comment]
Hi @Automanmm, I've shared the code to your email address.

**Comment by GSidiropoulos** [comment]
Hi @cliang1453. Could you please share the code and gazetteer for the distant labels generation? My email is g.sidiropoulos@uva.nl. Thanks in advance!

**Comment by cliang1453** [comment]
Hi @GSidiropoulos, sent ✅

**Comment by 2016bits** [comment]
Hi @cliang1453. Could you please share the code and gazetteer for the distant label generation? My email is 1835154145@qq.com. Thanks in advance!

**Comment by XiPotatonium** [comment]
Hi @cliang1453. Thanks for your great work. Could you please share the code and gazetteer for generating distant labels? My email is xipotatonium@outlook.com. Thanks in advance.

**Comment by cliang1453** [comment]
Hi @XiPotatonium @2016bits , sent.

**Comment by mingboiz** [comment]
Hi @cliang1453 , thank you for your work - could you please share the gazetteers and distant label generation code to me as well? My email is ming@u.nus.edu. Thank you in advance!
