### ISSUE TITLE
What if i would like to use Electra model from  huggingface transformers?

### ISSUE THREAD

**Issue by marcusau** [cliang1453/BOND#2]
Hi, 

   Thanks for the amazing work.

    Just one simple question, if i would like to use electra model from transformers library , besides, the BertConfig, tokenizers, and model load are all converted into electra tools,   any other code i have to edit in order to make the electra into Bond model? 

    Thanks a lot.

Marcus

**Comment by cliang1453** [comment]
Hi, 

I think you mainly need to edit ``convert_examples_to_features`` in data_utils.py to fit the Electra input pattern, and edit ``modeling_roberta.py``.

**Comment by marcusau** [comment]
Sure, Thanks a lot.

Also , my understanding is .   first run the stage 1 by run_ner.py , and then on the top of the stage 1 output  to run self-learning.py. 

Please correct me if i am wrong.

Thanks a lot.

Marcus

**Comment by cliang1453** [comment]
Hi Marcus, sorry for the confusion. Running ``run_self_training_ner.py`` will directly produce the two-stage results. You don't need to run it on top of the stage 1 output.

**Comment by marcusau** [comment]
got it .

Thanks a lot.

What i just wanna know is ...... If i dont have the hp label in my dataset. how to produce it ??

Thanks a lot :)

**Comment by cliang1453** [comment]
Hi Marcus, we produced hp labels for CoNLL03 using pos tagging and rule-based method, and see little improvement unfortunately. Hence, we decided not to use hp labels for training, by not setting ``args.self_training_hp_label`` to be 2 or 3 (https://github.com/cliang1453/BOND/blob/3651a92adedbd53bbc6210fade7f688b171d6434/model_utils.py#L48). We plan to remove these redundant codes that cause confusion.

**Comment by marcusau** [comment]
thanks.. 

If hp label is not so useful in BOND,  I can run the Bond training by run_self_training_ner.py and set args.self_training_hp_label not to be  2 or 3 in the line 570   of  run_self_training_ner.py.
    parser.add_argument('--self_training_hp_label', type = float, default = 0, help = 'use high precision label.')

Thanks for that 👍 

Marcus
