### ISSUE TITLE
About the gazetteers information and distant label generation code

### ISSUE THREAD

**Issue by zyz0000** [cliang1453/BOND#21]
Thanks for your great work! Could you please provide the gazetteers information and distant label generation code?

**Comment by cliang1453** [comment]
Hi @zyz0000, could you please provide your email address?

**Comment by zyz0000** [comment]
> Hi @zyz0000, could you please provide your email address?

1784608154@qq.com  Thank you so much!

**Comment by cliang1453** [comment]
No problem. Sent.

**Comment by sc-lj** [comment]
could you sent me this code? 779365135@qq.com  Thank you so much!
