### ISSUE TITLE
one question about "tags_hp" in the preprocessing stage

### ISSUE THREAD

**Issue by marcusau** [cliang1453/BOND#3]
Hi,

   In the /data_utils.py ,there is a strange point i would like to ask before trying implement stage 1. 

   In the function of "read_examples_from_file", there is a command  hp_labels = item["tags_hp"]

   However, i cannot search '"tags_hp" in the train.json of the five datasets you provided.

   Would you mind to explain the function of this 'tags_hp' ?  Thanks a lot.

    def read_examples_from_file(data_dir, mode):
    
        file_path = os.path.join(data_dir, "{}.json".format(mode))
        guid_index = 1
        examples = []

        with open(file_path, 'r') as f:
            data = json.load(f)
        
            for item in data:
                words = item["str_words"]
                labels = item["tags"]
                if "tags_hp" in labels:
                    hp_labels = item["tags_hp"]
                else:
                    hp_labels = [None]*len(labels)
                examples.append(InputExample(guid="%s-%d".format(mode, guid_index), words=words, labels=labels, hp_labels=hp_labels))
                guid_index += 1
    
        return examples

Marcus

**Comment by cliang1453** [comment]
Hi, thanks for the question. we'll soon provide some detailed comments on how to use these hp labels.

**Comment by marcusau** [comment]
Thanks for that  because i am a big fans of distant supervised NER and  I have prepared a traditional Chinese datasets with ~60000 sentences generated from financial news articles produced by Hong Kong Economic Times (the second largest financial newspaper in HK).

My role is now NLP engineer inside Hong Kong Economic Times and the NER datasets produced by me are labelled with 22 NER classes, including, ORG, PERSON, CONCEPT, FIN (financial instruments), SLOGAN , LOC etc,.....

Ofz , these NER labels are all annotated by me , thus, there are much noises inside the datasets.

If i can incorporate the concept of hp labels into my dataset, then would be perfect to try the BOND algo in a big production environment.

Thanks a lot.

Marcus 

marcus.auchiming@gmail.com

**Comment by cliang1453** [comment]
Hi Marcus, thanks for the comment and I'm glad this is something we can help with! We will update these doc ASAP :)

**Comment by marcusau** [comment]
Thanks a lot.

Any idea how to generate hp label by myself?

Or The codes in the self-learning and data-util will produce hp labels for me ?

Thanks a lot

Marcus

**Comment by cliang1453** [comment]
Hi Marcus, you may try using some high coverage KB or some domain heuristics to further improve your "noisy labels". As I said in another thread, we didn't use additional high precision label information unfortunately.

**Comment by marcusau** [comment]
sure, for label, i can do it by myself.

Thanks a lot.

Marcus

**Comment by cliang1453** [comment]
No problem. I'll go ahead and close both threads.
