### ISSUE TITLE
two questions about your paper

### ISSUE THREAD

**Issue by xilinniao123** [cliang1453/BOND#4]
thanks for sharing! i want to ask two quesions:
1、 the teacher model just initialized with the student model and generate pseudo labels,so why use it ? why not just use the student model to generate pseudo labels? 
2、 if I have small full annotated data how to comine with you model?
thanks

**Comment by cliang1453** [comment]
Thanks for you questions!

1. You are correct, it is indeed "student self-training". We choose to use a separate teacher model for flexibility concerns, as we can add other design choices on the teacher model (e.g. mean teacher, vat, etc). 
2. I assume you are talking about the situation where you have partially annotated data. One choice is to generate pseudo-labels for the noisy data, and keep using the true labels for the annotated data. Or, the annotated data could serve for validation purpose: the teacher gets updated and generates a new set of pseudo-labels everytime the student achieves better validation performance. 

Hope this helps!
Chen
