### ISSUE TITLE
Reproducing distant labels with gazetteer information 

### ISSUE THREAD

**Issue by jeannefukumaru** [cliang1453/BOND#5]
Congratulations on this paper getting accepted into KDD 2020! 

I'm a Computer Science masters student at the National University of Singapore. I'm hoping to explore whether a better F1 score can be produced by improving the process of distant label generation. Would you have the gazetteers and code used to generate the distant labels to share? 

Happy to share my progress with this as it is a semester project I am looking at. I am reachable at e0576205@u.nus.edu

Thank you, 
Jeanne

**Comment by cliang1453** [comment]
Hi Jeanee, I've emailed you the gazetteers and distant label generation code.
