### ISSUE TITLE
what is the format of the dataset? how to convert any new dataset into this format?

### ISSUE THREAD

**Issue by abubakar-ucr** [cliang1453/BOND#9]
what is the format of the dataset? what are json keys, and how are IDs assigned? Do these correspond to BERT tokenizer or something else?
 how to convert any new dataset into this format?

**Comment by HMJiangGatech** [comment]
It is basically the CoNLL format https://simpletransformers.ai/docs/ner-data-formats/#text-file-in-conll-format
Only the fields “str_words” and “tag” are used.  Other fields are used in other projects and are not used in this repo. 
The “tag” is the index of labels, where the mapping is defined in “tag_to_id.json”
You can see how we process these files in
https://github.com/cliang1453/BOND/blob/60d4938f3a0b24d52aa36e6d95416cf676ef11c2/data_utils.py#L55-L74

The hp_tags are actually not used, and you can simply ignore it. It was originally designed for handling different weak label sources, where some weak labels were given higher weight as their quality is higher.
